# 01-3

## <span style="color:deeppink">마무리</span>

### 🍀 키워드로 끝내는 핵심 포인트

<span style="color:deepskyblue">특성</span>은 데이터를 표현하는 하나의 성질  
생선 데이터에서는 길이와 무게

<span style="color:deepskyblue">훈련</span> 머신러닌 알고리즘이 데이터에서 규칙을 찾는 과정

<span style="color:deepskyblue">K-최근접 이웃 알고리즘</span>은 간단한 머신러닝 알고리즘

<span style="color:deepskyblue">모델</span>은 머신러닝 프로그램에서 알고리즘이 구현된 객체  
종종 알고리즘 자체를 모델이라고 하기도 함

<span style="color:deepskyblue">정확도</span>는 정확한 답을 몇 개 맞혔는지 나타내는 값

### 🍀 핵심 패키지와 함수

#### <span style="color:blue"><u>matplotlib</u></span>

<span style="color:dodgerblue"> scatter()</span>는 산점도를 그리는 맷플롯립 함수  
처음 2개의 매개변수는 x와y축 값으로 전달  
marker는 기본값이 원이다

#### <span style="color:blue"><u>scikit-learn</u></span>

<span style="color:dodgerblue">KNeighborsClassifier()</span>는 k-최근접 이웃 분류 모델을 만드는 사이킷런 클래스이다.  
`n_neighbors`매개변수로 이웃의 개수를 지정하고 기본값은 5  
`p`는 거리를 재는 방법을 지정  
1:맨해튼 거리,2:유클리드 거리(기본값)  
`n_jobs`CPU코어 지정

<span style="color:dodgerblue">fit()</span> 사이킷런 모델을 훈련할 때 사용

<span style="color:dodgerblue">predict()</span> 사이킷런 모델을 훈련하고 예측할 때 사용

<span style="color:dodgerblue">score()</span>는 훈련된 사이킷런 모델의 성능을 측정 

# 02-1

## <span style="color:deeppink">마무리</span>

### 🍀 키워드로 끝내는 핵심 포인트

<span style="color:deepskyblue">지도학습</span> 입력과 타깃을 전달하여 모델을 훈련한 다음 다른 새로운 데이터를 예측하는데 사용  
K-최근접 이웃 알고리즘:지도학습

<span style="color:deepskyblue">비지도학습</span> 타깃 데이터가 없음  
예측하는 것이 아니라 특징을 찾는데 사용

<span style="color:deepskyblue">훈련 세트</span> 훈련할 때 사용

<span style="color:deepskyblue">테스트 세트</span> 전체 데이터의 20~30%를 사용하는 경우가 많음

### 🍀 핵심 패키지와 함수

#### <span style="color:blue"><u>numpy</u></span>

<span style="color:dodgerblue"> seed()</span>는 넘파이에서 난수를 생성하기 위한 정수 초깃값을 지정  
랜덤 함수의 결과를 동일하게 재현하고 싶을 때

<span style="color:dodgerblue"> arange()</span>는 일정한 간격의 정수 또는 실수 배열을 만들고 기본 간격은 1이다.

In [1]:
import numpy as np
print(np.arange(3))

[0 1 2]


In [3]:
print(np.arange(1,3))

[1 2]


In [4]:
print(np.arange(1,3,0.2))

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8]


<span style="color:dodgerblue"> shuffle()</span>는 주어진 배열을 무작위로 섞음

In [12]:
arr=np.array([[1,2],[3,4],[5,6]])

In [14]:
np.random.shuffle(arr)
arr

array([[5, 6],
       [3, 4],
       [1, 2]])

# 02-2

## <span style="color:deeppink">마무리</span>

### 🍀 키워드로 끝내는 핵심 포인트

<span style="color:deepskyblue">데이터 전처리</span> 데이터 가공하는 단계

<span style="color:deepskyblue">표준점수</span> 특성의 평균을 빼고 표준편차로 나눈다.

<span style="color:deepskyblue">브로드캐스팅</span> 크기가 다른 넘파이 배열을 자동으로 확장하는 기능

### 🍀 핵심 패키지와 함수

#### <span style="color:blue"><u>scikit-learn</u></span>

<span style="color:dodgerblue"> train_test_split()</span>는 훈련 세트와 테스트 세트로 나누는 함수  
테스트 세트로 나누는 비율은 `test_size` 매개변수에서 지정할 수 있음  
`shuffle`매개변수로 훈련 세트와 테스트 세트로 나누기 전에 무작위로 섞을지 여부 결정  
`stratify`매개변수에 클래스 레이블이 담긴 배열을 넣으면 클래스 비율이 맞게 나눈다.

<span style="color:dodgerblue"> kneighbors()</span>는 K-최근접 이웃 객체의 메서드이다.  
입력한 데이터의 가장 가까운 이웃을 찾아 거리와 이웃 샘플의 인덱스를 반환한다.  
`return_distance`매개변수를 False로 지정하면 인덱스만 반환하고 거리는 반환하지 않는다. 기본은 True

# 03-1

## <span style="color:deeppink">마무리</span>

### 🍀 키워드로 끝내는 핵심 포인트

<span style="color:deepskyblue">회귀</span>는 임의의 수치를 에측하는 문제

<span style="color:deepskyblue">k-최근접 이웃 회귀</span>는 k-최근접 이웃 알고리즘을 사용해 회귀 문제를 푼다  
가장 가까운 이웃 샘플을 찾고 평균하여 예측으로 

<span style="color:deepskyblue">결정계수</span> 회귀 문제의 성능 측정 도구, 1에 가까울수록 좋음

<span style="color:deepskyblue">과대적합</span>은 훈련 세트의 성능이 테스트 세트의 성능보다 훨씬 좋을 때

<span style="color:deepskyblue">과소적합</span>은 테스트 세트의 성능이 훈련 세트의 성능보다 좋을 때나 모두 낮을 때

### 🍀 핵심 패키지와 함수

#### <span style="color:blue"><u>scikit-learn</u></span>

<span style="color:dodgerblue"> KNeighborsRegressor()</span>는 k-최근접 이웃 회귀 모델을 만드는 사이킷런 클래스  
`n_neighbors`는 이웃의 개수를 지정하는 매개변수이고 기본은 5

<span style="color:dodgerblue">mean_absolute_error()</span>는 회귀 모델의 평균 절댓값 오차를 계산  
타깃,예측값 순서로 적어야 함  
`mean_squared_error()`평균 제곱 오차를 계산하는 함수 

#### <span style="color:blue"><u>numpy</u></span>

<span style="color:dodgerblue">reshape()</span>는 배열의 크기를 바꾸는 메서드

# 03-2

## <span style="color:deeppink">마무리</span>

### 🍀 키워드로 끝내는 핵심 포인트

<span style="color:deepskyblue"></span>

<span style="color:deepskyblue"></span>

<span style="color:deepskyblue"></span>

<span style="color:deepskyblue"></span>

### 🍀 핵심 패키지와 함수

#### <span style="color:blue"><u>scikit-learn</u></span>

<span style="color:dodgerblue"> ()</span>

# 03-3

## <span style="color:deeppink">마무리</span>

### 🍀 키워드로 끝내는 핵심 포인트

<span style="color:deepskyblue"></span>

<span style="color:deepskyblue"></span>

<span style="color:deepskyblue"></span>

<span style="color:deepskyblue"></span>

<span style="color:deepskyblue"></span>

### 🍀 핵심 패키지와 함수

#### <span style="color:blue"><u></u></span>

<span style="color:dodgerblue"> ()</span>

#### <span style="color:blue"><u></u></span>

<span style="color:dodgerblue"> ()</span>

<span style="color:dodgerblue"> ()</span>

<span style="color:dodgerblue"> ()</span>

# 04-1

## <span style="color:deeppink">마무리</span>
### 🍀 키워드로 끝내는 핵심 포인트
<span style="color:deepskyblue"></span>
### 🍀 핵심 패키지와 함수
#### <span style="color:blue"><u></u></span>
<span style="color:dodgerblue"> ()</span>